#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser
from dotenv import dotenv_values
from os import path
import http.client, urllib

class Pushover(object):
    def __init__(self):
        self.token = None
        self.user = None
        self.default_device = None
        self.default_title = None
        self.load_config()

    def load_config(self):
        """Load in the configuration from the .env file."""
        env_path = path.join(path.dirname(path.realpath(__file__)), '.env')
        config = dotenv_values(env_path)

        self.token = config['PUSHOVER_APP_TOKEN']
        self.user = config['PUSHOVER_USER_KEY']

        if 'DEFAULT_DEVICE' in config:
            self.default_device = config['DEFAULT_DEVICE']

        if 'DEFAULT_TITLE' in config:
            self.default_title = config['DEFAULT_TITLE']

    def main(self):
        """Parse the notification and send it via pushover."""
        notification = self.get_notification()
        self.send(notification)

    def get_notification(self):
        """Return the notification to send."""
        parser = ArgumentParser()
        parser.add_argument('--error', action='store_true', help='Display error message')
        parser.add_argument('--title', type=str, help='Notification title')
        parser.add_argument('--devices', type=str, help='Device(s) to send to')
        parser.add_argument('message', type=str, help='Notification message')
        args = parser.parse_args()

        notification = {
            'message': args.message
        }

        if args.title:
            notification['title'] = args.title
        elif self.default_title:
            notification['title'] = self.default_title

        if args.error:
            notification['message'] = 'Error: %s' % message

        if args.devices:
            notification['devices'] = args.devices
        elif self.default_device:
            notification['devices'] = self.default_device

        return notification

    def send(self, notification):
        """Send the notification."""

        data = {
            'token': self.token,
            'user': self.user,
            'message': notification['message']
        }

        if 'title' in notification:
            data['title'] = notification['title']

        if 'devices' in notification:
            data['device'] = notification['devices']

        conn = http.client.HTTPSConnection('api.pushover.net:443')
        conn.request(
            'POST',
            '/1/messages.json',
            urllib.parse.urlencode(data),
            { 'Content-type': 'application/x-www-form-urlencoded' }
        )
        conn.getresponse()

if __name__ == '__main__':
    Pushover().main()
